### ISSUE TITLE
Support for BitTorrent v2 protocol

### ISSUE THREAD

**Issue by AnimMouse** [AnimMouse/torrent-webseed-creator#5]
Waiting for mktorrent to implement BitTorrent v2 protocol or switch to another torrent creation program that has support for BitTorrent v2 protocol.

**Comment by AnimMouse** [comment]
Possible Candidates:
https://github.com/pobrn/mktorrent/issues/29
https://github.com/rsnitsch/py3createtorrent/issues/6

Let's see who will implement it first.

**Comment by fbdtemme** [comment]
Please consider my new torrent creation program [torrenttools](https://github.com/fbdtemme/torrenttools) with support for v2 and hybrid protocols as a possible candidate:

**Comment by AnimMouse** [comment]
@fbdtemme Wow, nice program you made there, will definitely consider.

**Comment by AnimMouse** [comment]
BitTorrent v2 has been implemented through torrenttools on cab55f84f59ec912b8a47fe202adcd275040bb20 tested on b1d5fa9bf1dd86dd92a077abc0212d9744d13c36. Thanks, @fbdtemme.
